service: api-refund

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-2
  stage: production
  memorySize: 512
  timeout: 30
  environment:
    NODE_ENV: production

functions:
  app:
    handler: dist/lambda.handler
    events:
      - httpApi: '*'

plugins:
  - serverless-offline