service: api-refund

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-2
  stage: production
  memorySize: 512
  timeout: 30
  versionFunctions: true
  environment:
    NODE_ENV: production

functions:
  app:
    handler: src/lambda.handler
    events:
      - httpApi:
          path: /{proxy+}
          method: ANY

custom:
  esbuild:
    bundle: true
    minify: false
    target: node20
    platform: node
    concurrency: 10
    exclude:
      - aws-sdk
    external:
      - class-transformer/storage
      - '@nestjs/microservices'
      - '@nestjs/microservices/microservices-module'
      - '@nestjs/websockets/socket-module'

plugins:
  - serverless-esbuild
