export enum TaxCouponStatus {
  UPLOAD = 'UPLOAD',
  TEXTRACT_INITIATED = 'TEXTRACT_INITIATED',
  TEXTRACT_COMPLETED = 'TEXTRACT_COMPLETED',
  AI_INITIATED = 'AI_INITIATED',
  AI_COMPLETED = 'AI_COMPLETED',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
}
